### ISSUE TITLE
import _weakref failed

### ISSUE THREAD

**Issue by AnWD** [PacificBiosciences/HBAR-DTK#12]
Hello,everyone:
         I have installed HBAR-DTK in a sge environment. When I ran it with the default cfg,  it failed with a message "ImportError:No Module named _weakref". And I was using the python virtual environment.
It seems that there is no error,when I imported  _weakref in a single node.
        Coule you help us,please?
yours,
                                                                                                                           JingY

**Comment by rhallPB** [comment]
HBAR-DTK is not under active development, for a standard HGAP pipeline I would suggest using the HGAP.3 protocol in SMRT Analysis. If you are interested in large genome / diploid assembly I would recommend looking at FALCON https://github.com/PacificBiosciences/FALCON.
