### ISSUE TITLE
about  CA_best_edge_to_GML.py

### ISSUE THREAD

**Issue by orangeSi** [PacificBiosciences/HBAR-DTK#13]
hi,
     when I use CA_best_edge_to_GML.py,an error happen like  "
     Traceback (most recent call last):
     File "CA_best_edge_to_GML.py", line 51, in <module>
     id1, lib_id, best5, o1, best3, o3 = l
     ValueError: too many values to unpack"
So I chage line 51 to " id1, lib_id, best5, o1, best3, o3 = l[:6]" ,and line 51 work ,but another error happen "
Traceback (most recent call last):
  File "CA_best_edge_to_GML.py", line 52, in <module>
    G.add_node(id1, unitig="utg%s" % frg_to_tig[id1])
KeyError: '8'
"
so how to solve it ?

Thanks!
Si

**Comment by rhallPB** [comment]
Looks like a mismatch between the version of CA that the script is expecting and what is in the path. For a version of the script that works with more up to date versions of CA:
https://github.com/PacificBiosciences/Bioinformatics-Training/blob/master/scripts/CeleraToGephi.py
