### ISSUE TITLE
Install error for pbdagcon

### ISSUE THREAD

**Issue by xogur** [PacificBiosciences/HBAR-DTK#14]
Hi,

I am trying to install pbdagcon according to instruction. But, I get an error message like at below. Can Anybody help me to figure it out? Thank you!

xogur

$ pip install git+https://github.com/PacificBiosciences/pbdagcon.git#pbdagcon
Collecting git+https://github.com/PacificBiosciences/pbdagcon.git#pbdagcon
  Cloning https://github.com/PacificBiosciences/pbdagcon.git to /private/var/folders/l7/7kh64jhj0_7gbr_c7k2xk1980000gp/T/pip-j1QCba-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/private/var/folders/l7/7kh64jhj0_7gbr_c7k2xk1980000gp/T/pip-j1QCba-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/l7/7kh64jhj0_7gbr_c7k2xk1980000gp/T/pip-j1QCba-build/

**Comment by pb-jchin** [comment]
This repository is obsoleted. You need to post your issue in the other related repository.
